[window]
opacity = 0.9
decorations = "none"
dynamic_padding = false
startup_mode = "Windowed"

[window.padding]
x = 10
y = 10

[font]
size = 11.0

[font.normal]
family = "Noto Sans Mono"
style = "Regular"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.cursor]
text = "#000000"
cursor = "#ffffff"

[colors.normal]
black = "#1e1e2e"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#cdd6f4"

[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#ffffff"

[scrolling]
history = 10000
multiplier = 3

[mouse]
hide_when_typing = true

[env]
TERM = "xterm-256color"
